---
- name: 'Packages: Install'
  yum: name={{ item }} state=latest
  with_items:
    - php
    - php-mysql

- name: 'Packages: Configure'
  ini_file:
    dest: /etc/php.ini
    section: PHP
    option: cgi.fix_pathinfo
    value: 0
    state: present
  notify: restart httpd