---
# This playbook contains common plays that will be run on all nodes.

- include: pre.yml
- include: install_httpd.yml
- include: install_php-fpm.yml
- include: install_mariadb.yml
- include: configure_httpd_for_php-fpm.yml
- include: configure_php_for_mysql.yml