---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: 'MySQL: WordPress database'
      command: >
        mysql -e '
        CREATE DATABASE IF NOT EXISTS `wordpress`;
        CREATE USER `username`@`localhost` IDENTIFIED BY "password";
        GRANT ALL PRIVILEGES ON `wordpress`.* TO `username`@`localhost`;
        FLUSH PRIVILEGES;
        '

    - name: 'Wget: WordPress'
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress-latest.tar.gz

    - name: 'Unarchive: WordPress'
      unarchive:
        src: /tmp/wordpress-latest.tar.gz
        dest: /var/www/html/
        extra_opts: ['--strip-components=1']

    - name: 'DocumentRoot: Permissions'
      file:
        path: /var/www/html/
        owner: root
        group: apache
        mode: 'u=rwX,g=rwX,o=rX'
        recurse: yes
